a0_my_stack is done
JokerJudge/py111_lab pull request #3
Opened 2019-12-15 09:30 UTC by JokerJudge

Сделал первое задание. 
Тесты пройдены. Скриншот приложил.
![a0_my_stack](https://user-images.githubusercontent.com/45399443/70860734-7df31880-1f36-11ea-9cc4-f284a3b0fb12.png)

2019-12-15 11:16 UTC, JokerJudge commented
Второе и третье задание сделано
![a1_my_queue](https://user-images.githubusercontent.com/45399443/70861892-7f780d00-1f45-11ea-89b7-20e1b0eaee79.png)
![a2_priority_queue](https://user-images.githubusercontent.com/45399443/70861893-7f780d00-1f45-11ea-9859-450878d19b3e.png)

2019-12-15 19:58 UTC, JokerJudge commented
Четвертое задание
![a3_check_brackets](https://user-images.githubusercontent.com/45399443/70868121-5465db80-1f8e-11ea-93b4-73d1a7c8a6b7.png)

2019-12-16 05:49 UTC, aeksei approved these changes

2019-12-16 05:49 UTC, aeksei commented on Tasks/a0_my_stack.py
> +	try:
В будущем, старайтесь из бегать такой общей конструкции try-except, которая во-первых отлавливает все ошибки, и во-вторых ничего не выводит о них. 
В данном простейшем случае ничего страшного нет, а вот если программа будет больше и сложнее, то очень трудно будет найти ошибку в ней

2019-12-16 06:13 UTC, aeksei requested changes

2019-12-16 06:13 UTC, aeksei commented on Tasks/a2_priority_queue.py
> +	min = 5
Эта переменная отвечает за количество приоритетов в очереди? Если да, то я бы её вынес в начало файла и задавал там. Например, можно задать в качестве константы MIN_QUEUE_PRIORITY = 5, и уже в программе сделать локальный минимум и работать с ним. Плюс избегайте использования перезаписывания встроенной функции `min`.

Плюс попробуйте реализовать вывод элемента из очереди за один проход по циклу.

2019-12-22 18:33 UTC, JokerJudge commented
Переделал в соответствии с рекомендациями
![a0_my_stack_V_2](https://user-images.githubusercontent.com/45399443/71325769-bda39c80-2502-11ea-9adc-90229c8711b8.png)
![a2_priority_queue_V_2](https://user-images.githubusercontent.com/45399443/71325770-bda39c80-2502-11ea-8011-59ed8fa64187.png)

2019-12-23 06:24 UTC, aeksei commented on Tasks/a2_priority_queue.py
> +	global queue, MIN_QUEUE_PRIORITY
Тут уже не обязательно, было кидать MIN_QUEUE_PRIORITY в global
MIN_QUEUE_PRIORITY она не переопределяется в локальной области видимости функции, поэтому будет искать её в глобальной

2019-12-23 06:26 UTC, aeksei approved these changes
Можете мержить тогда

2020-01-19 15:05 UTC, merged